//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModbusServiceHost.DynamicCacheServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommandResultBase", Namespace="http://schemas.datacontract.org/2004/07/ModbusServiceLibrary.CommandResult")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModbusServiceHost.DynamicCacheServiceReference.ConnectToRtuResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModbusServiceHost.DynamicCacheServiceReference.ConnectToRtuFailedResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModbusServiceHost.DynamicCacheServiceReference.ReadSingleDiscreteSignalResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModbusServiceHost.DynamicCacheServiceReference.ReadSingleDiscreteSignalFailedResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModbusServiceHost.DynamicCacheServiceReference.ReadSingleAnalogSignalResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModbusServiceHost.DynamicCacheServiceReference.ReadSingleAnalogSignalFailedResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModbusServiceHost.DynamicCacheServiceReference.WriteDiscreteSignalCommandResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModbusServiceHost.DynamicCacheServiceReference.WriteAnalogSignalCommandResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModbusServiceHost.DynamicCacheServiceReference.CommandProcessorNotFoundResult))]
    public partial class CommandResultBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectToRtuResult", Namespace="http://schemas.datacontract.org/2004/07/ModbusServiceLibrary.CommandResult")]
    [System.SerializableAttribute()]
    public partial class ConnectToRtuResult : ModbusServiceHost.DynamicCacheServiceReference.CommandResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RtuIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RtuId {
            get {
                return this.RtuIdField;
            }
            set {
                if ((this.RtuIdField.Equals(value) != true)) {
                    this.RtuIdField = value;
                    this.RaisePropertyChanged("RtuId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectToRtuFailedResult", Namespace="http://schemas.datacontract.org/2004/07/ModbusServiceLibrary.CommandResult")]
    [System.SerializableAttribute()]
    public partial class ConnectToRtuFailedResult : ModbusServiceHost.DynamicCacheServiceReference.CommandResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RtuIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RtuId {
            get {
                return this.RtuIdField;
            }
            set {
                if ((this.RtuIdField.Equals(value) != true)) {
                    this.RtuIdField = value;
                    this.RaisePropertyChanged("RtuId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReadSingleDiscreteSignalResult", Namespace="http://schemas.datacontract.org/2004/07/ModbusServiceLibrary.CommandResult")]
    [System.SerializableAttribute()]
    public partial class ReadSingleDiscreteSignalResult : ModbusServiceHost.DynamicCacheServiceReference.CommandResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RtuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SignalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RtuId {
            get {
                return this.RtuIdField;
            }
            set {
                if ((this.RtuIdField.Equals(value) != true)) {
                    this.RtuIdField = value;
                    this.RaisePropertyChanged("RtuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SignalId {
            get {
                return this.SignalIdField;
            }
            set {
                if ((this.SignalIdField.Equals(value) != true)) {
                    this.SignalIdField = value;
                    this.RaisePropertyChanged("SignalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReadSingleDiscreteSignalFailedResult", Namespace="http://schemas.datacontract.org/2004/07/ModbusServiceLibrary.CommandResult")]
    [System.SerializableAttribute()]
    public partial class ReadSingleDiscreteSignalFailedResult : ModbusServiceHost.DynamicCacheServiceReference.CommandResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RtuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SignalIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RtuId {
            get {
                return this.RtuIdField;
            }
            set {
                if ((this.RtuIdField.Equals(value) != true)) {
                    this.RtuIdField = value;
                    this.RaisePropertyChanged("RtuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SignalId {
            get {
                return this.SignalIdField;
            }
            set {
                if ((this.SignalIdField.Equals(value) != true)) {
                    this.SignalIdField = value;
                    this.RaisePropertyChanged("SignalId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReadSingleAnalogSignalResult", Namespace="http://schemas.datacontract.org/2004/07/ModbusServiceLibrary.CommandResult")]
    [System.SerializableAttribute()]
    public partial class ReadSingleAnalogSignalResult : ModbusServiceHost.DynamicCacheServiceReference.CommandResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RtuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SignalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SignalValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RtuId {
            get {
                return this.RtuIdField;
            }
            set {
                if ((this.RtuIdField.Equals(value) != true)) {
                    this.RtuIdField = value;
                    this.RaisePropertyChanged("RtuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SignalId {
            get {
                return this.SignalIdField;
            }
            set {
                if ((this.SignalIdField.Equals(value) != true)) {
                    this.SignalIdField = value;
                    this.RaisePropertyChanged("SignalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SignalValue {
            get {
                return this.SignalValueField;
            }
            set {
                if ((this.SignalValueField.Equals(value) != true)) {
                    this.SignalValueField = value;
                    this.RaisePropertyChanged("SignalValue");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReadSingleAnalogSignalFailedResult", Namespace="http://schemas.datacontract.org/2004/07/ModbusServiceLibrary.CommandResult")]
    [System.SerializableAttribute()]
    public partial class ReadSingleAnalogSignalFailedResult : ModbusServiceHost.DynamicCacheServiceReference.CommandResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RtuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SignalIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RtuId {
            get {
                return this.RtuIdField;
            }
            set {
                if ((this.RtuIdField.Equals(value) != true)) {
                    this.RtuIdField = value;
                    this.RaisePropertyChanged("RtuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SignalId {
            get {
                return this.SignalIdField;
            }
            set {
                if ((this.SignalIdField.Equals(value) != true)) {
                    this.SignalIdField = value;
                    this.RaisePropertyChanged("SignalId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WriteDiscreteSignalCommandResult", Namespace="http://schemas.datacontract.org/2004/07/ModbusServiceLibrary.CommandResult")]
    [System.SerializableAttribute()]
    public partial class WriteDiscreteSignalCommandResult : ModbusServiceHost.DynamicCacheServiceReference.CommandResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RtuIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RtuId {
            get {
                return this.RtuIdField;
            }
            set {
                if ((this.RtuIdField.Equals(value) != true)) {
                    this.RtuIdField = value;
                    this.RaisePropertyChanged("RtuId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WriteAnalogSignalCommandResult", Namespace="http://schemas.datacontract.org/2004/07/ModbusServiceLibrary.CommandResult")]
    [System.SerializableAttribute()]
    public partial class WriteAnalogSignalCommandResult : ModbusServiceHost.DynamicCacheServiceReference.CommandResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RtuIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RtuId {
            get {
                return this.RtuIdField;
            }
            set {
                if ((this.RtuIdField.Equals(value) != true)) {
                    this.RtuIdField = value;
                    this.RaisePropertyChanged("RtuId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommandProcessorNotFoundResult", Namespace="http://schemas.datacontract.org/2004/07/ModbusServiceLibrary.CommandResult")]
    [System.SerializableAttribute()]
    public partial class CommandProcessorNotFoundResult : ModbusServiceHost.DynamicCacheServiceReference.CommandResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModbusServiceHost.DynamicCacheServiceReference.RtuCommandBase RtuCommandField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModbusServiceHost.DynamicCacheServiceReference.RtuCommandBase RtuCommand {
            get {
                return this.RtuCommandField;
            }
            set {
                if ((object.ReferenceEquals(this.RtuCommandField, value) != true)) {
                    this.RtuCommandField = value;
                    this.RaisePropertyChanged("RtuCommand");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RtuCommandBase", Namespace="http://schemas.datacontract.org/2004/07/ModbusServiceLibrary.RtuCommands")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModbusServiceHost.DynamicCacheServiceReference.ConnectToRtuCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModbusServiceHost.DynamicCacheServiceReference.ReadSingleSignalCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModbusServiceHost.DynamicCacheServiceReference.WriteAnalogSignalCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModbusServiceHost.DynamicCacheServiceReference.WriteDiscreteSignalCommand))]
    public partial class RtuCommandBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectToRtuCommand", Namespace="http://schemas.datacontract.org/2004/07/ModbusServiceLibrary.RtuCommands")]
    [System.SerializableAttribute()]
    public partial class ConnectToRtuCommand : ModbusServiceHost.DynamicCacheServiceReference.RtuCommandBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RtuIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RtuId {
            get {
                return this.RtuIdField;
            }
            set {
                if ((this.RtuIdField.Equals(value) != true)) {
                    this.RtuIdField = value;
                    this.RaisePropertyChanged("RtuId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReadSingleSignalCommand", Namespace="http://schemas.datacontract.org/2004/07/ModbusServiceLibrary.RtuCommands")]
    [System.SerializableAttribute()]
    public partial class ReadSingleSignalCommand : ModbusServiceHost.DynamicCacheServiceReference.RtuCommandBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RtuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SignalIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RtuId {
            get {
                return this.RtuIdField;
            }
            set {
                if ((this.RtuIdField.Equals(value) != true)) {
                    this.RtuIdField = value;
                    this.RaisePropertyChanged("RtuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SignalId {
            get {
                return this.SignalIdField;
            }
            set {
                if ((this.SignalIdField.Equals(value) != true)) {
                    this.SignalIdField = value;
                    this.RaisePropertyChanged("SignalId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WriteAnalogSignalCommand", Namespace="http://schemas.datacontract.org/2004/07/ModbusServiceLibrary.RtuCommands")]
    [System.SerializableAttribute()]
    public partial class WriteAnalogSignalCommand : ModbusServiceHost.DynamicCacheServiceReference.RtuCommandBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RtuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SignalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueToWriteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RtuId {
            get {
                return this.RtuIdField;
            }
            set {
                if ((this.RtuIdField.Equals(value) != true)) {
                    this.RtuIdField = value;
                    this.RaisePropertyChanged("RtuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SignalId {
            get {
                return this.SignalIdField;
            }
            set {
                if ((this.SignalIdField.Equals(value) != true)) {
                    this.SignalIdField = value;
                    this.RaisePropertyChanged("SignalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValueToWrite {
            get {
                return this.ValueToWriteField;
            }
            set {
                if ((this.ValueToWriteField.Equals(value) != true)) {
                    this.ValueToWriteField = value;
                    this.RaisePropertyChanged("ValueToWrite");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WriteDiscreteSignalCommand", Namespace="http://schemas.datacontract.org/2004/07/ModbusServiceLibrary.RtuCommands")]
    [System.SerializableAttribute()]
    public partial class WriteDiscreteSignalCommand : ModbusServiceHost.DynamicCacheServiceReference.RtuCommandBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RtuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SignalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RtuId {
            get {
                return this.RtuIdField;
            }
            set {
                if ((this.RtuIdField.Equals(value) != true)) {
                    this.RtuIdField = value;
                    this.RaisePropertyChanged("RtuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SignalId {
            get {
                return this.SignalIdField;
            }
            set {
                if ((this.SignalIdField.Equals(value) != true)) {
                    this.SignalIdField = value;
                    this.RaisePropertyChanged("SignalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DynamicCacheServiceReference.IDynamicCacheManagerService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IDynamicCacheManagerService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDynamicCacheManagerService/ProcessCommandResult")]
        void ProcessCommandResult(ModbusServiceHost.DynamicCacheServiceReference.CommandResultBase commandResult);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDynamicCacheManagerService/ProcessCommandResult")]
        System.Threading.Tasks.Task ProcessCommandResultAsync(ModbusServiceHost.DynamicCacheServiceReference.CommandResultBase commandResult);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDynamicCacheManagerServiceChannel : ModbusServiceHost.DynamicCacheServiceReference.IDynamicCacheManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DynamicCacheManagerServiceClient : System.ServiceModel.ClientBase<ModbusServiceHost.DynamicCacheServiceReference.IDynamicCacheManagerService>, ModbusServiceHost.DynamicCacheServiceReference.IDynamicCacheManagerService {
        
        public DynamicCacheManagerServiceClient() {
        }
        
        public DynamicCacheManagerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DynamicCacheManagerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DynamicCacheManagerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DynamicCacheManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ProcessCommandResult(ModbusServiceHost.DynamicCacheServiceReference.CommandResultBase commandResult) {
            base.Channel.ProcessCommandResult(commandResult);
        }
        
        public System.Threading.Tasks.Task ProcessCommandResultAsync(ModbusServiceHost.DynamicCacheServiceReference.CommandResultBase commandResult) {
            return base.Channel.ProcessCommandResultAsync(commandResult);
        }
    }
}
