//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelWcfServiceLibrary.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbCronExpression
    {
        public int cron_id { get; set; }
        public string cron_name { get; set; }
        public System.DateTime cron_start { get; set; }
        public System.DateTime cron_end { get; set; }
        public int recurrence_period { get; set; }
        public int recurrence_type { get; set; }
    }
}
