//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelWcfServiceLibrary.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DbMapping()
        {
            this.DbDiscreteValueToStates = new HashSet<DbDiscreteValueToState>();
            this.DbSignals = new HashSet<DbSignal>();
        }
    
        public int mapping_id { get; set; }
        public string mapping_name { get; set; }
        public Nullable<float> K { get; set; }
        public Nullable<float> N { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbDiscreteValueToState> DbDiscreteValueToStates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbSignal> DbSignals { get; set; }
    }
}
