//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelWcfServiceLibrary.EntityDataModel
{
    using System.Collections.Generic;

    public partial class DbRtu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DbRtu()
        {
            this.DbSignals = new HashSet<DbSignal>();
        }
    
        public int rtu_id { get; set; }
        public string rtu_name { get; set; }
        public string ip_address { get; set; }
        public int rtu_port { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbSignal> DbSignals { get; set; }
    }
}
