//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelWcfServiceLibrary.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbScanPeriod
    {
        public int scan_id { get; set; }
        public string scan_name { get; set; }
        public System.TimeSpan scan_period { get; set; }
    }
}
